name: home_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  auto_route: ^4.2.0
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  dio: ^5.1.1
  connectivity_plus: ^2.3.6+1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  flutter_secure_storage: ^7.0.1
  flutter_html: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator:
  json_serializable: ^6.3.1
  auto_route_generator: ^4.2.0
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
